name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: .\build.bat
        shell: cmd
      - uses: softprops/action-gh-release@v2
        with:
          files: build/tf2vr_timefix.dll
